DROP TABLE IF EXISTS BOOKS;

CREATE TABLE BOOKS (  
id INT AUTO_INCREMENT  PRIMARY KEY,  
bookName VARCHAR(100) NOT NULL,  
bookAuthor VARCHAR(100) NOT NULL,
publicationHouse VARCHAR(100) NOT NULL,  
publishedYear VARCHAR(4) NOT NULL,
publishedMonth VARCHAR(2) NOT NULL
);  